//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_63130514.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhanVien
    {
        public int MaNhanVien { get; set; }
        public string Taikhoannv { get; set; }
        public string Matkhaunv { get; set; }
        public string TenNhanVien { get; set; }
        public string ChucVu { get; set; }
        public string SoDienThoai { get; set; }
        public string DiaChi { get; set; }
    }
}
